name: Docker Build
on:
  push:
    branches:
      - master
  workflow_dispatch: {}
  schedule:
    - cron: "0 8 * * 2"

permissions:
  packages: write

jobs:
  build_image:
    strategy:
      matrix:
        version: [1.16, 1.18, 1.19]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Replace version
        run: |
          sed -i 's/<VERSION>/${{ matrix.version }}/g' Dockerfile
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Build and push
        run: |
          docker build --push --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository }}:${{ matrix.version }} .
